version: '3'
services:
  postgres:
    image: 'postgres:12.11'
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'challenge'
  postgres-test:
    image: 'postgres:12.11'
    restart: always
    volumes:
      - db-test-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'challenge'

volumes:
  db-data:
  db-test-data:
